<img style="float: left;" src="./images/PalleAI-Banner1.png" width="800">

# Tensorflow Basics

**Low level Tensor Manipulation**
* Basically the underlying math behind all the deep learning
* In principle we can build entire deep learning model from start to finish with tensorflow
* But we dont have to, because Keras as a high level API simply lets us build deep learning models very quickly with predefined components (similar to lego bricks). Underlying these components however u can think that tensorflow is still doing all the low level math or tensor manipulation

## Import needed libraries 

In [1]:
#Basic Python packages for data wrangling if needed
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Tensorflow & Keras related packages
import tensorflow as tf

### What are Tensors

In [2]:
#To do anything in Tensorflow we will need tensors.
# Tensors are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors. 
# In fact tensors are merely a generalisation of scalars and vectors; 
# a scalar is a zero rank tensor, and a vector is a first rank tensor, a matrix is a 2 rank tensor.
# Its very similar to a numpy array

In [3]:
# Lets create some simple Tensors

In [4]:
x_t = tf.ones(shape=(4,3)) # create a tensor filled with ones
x_t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [5]:
# u can crerate an equivalent numpy array as follows

In [6]:
x_np = np.ones(shape=(4,3)) # see the similarity
x_np

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
x_t = tf.random.normal(shape=(3,2), mean=2, stddev=1) # tensorflow tensor filled with random values drawn from a normal distribution
x_t

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.8663423, 2.3426967],
       [2.954131 , 5.112155 ],
       [1.3903164, 3.826853 ]], dtype=float32)>

In [8]:
x_np = np.random.normal() # numpy array also filled with random values from normal distribution
x_np

array([[-0.48284067,  0.62533032],
       [ 0.99893408,  0.72374387],
       [ 0.38523369, -0.02088909]])

**Tensor math operations (Similar to Ufuncs (Universal functions) of Numpy)**

In [10]:
x_t = tf.ones(shape=(4,5))
x_t

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [11]:
x_t*3 # multiple tensor with a number

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]], dtype=float32)>

In [12]:
tf.square(x_t*3) # square a tensor

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]], dtype=float32)>

In [13]:
# Now lets see numpy way

In [14]:
x_np = np.ones((2,3))
x_np

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
x_np*3

array([[3., 3., 3.],
       [3., 3., 3.]])

In [16]:
np.square(x_np*3) 

array([[9., 9., 9.],
       [9., 9., 9.]])

In [17]:
np.square(x_t*3) # numpy array can operate on a tensorflow tensor

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]], dtype=float32)

In [18]:
tf.square(x_np*3) # or tensor can operate on a numpy array

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[9., 9., 9.],
       [9., 9., 9.]])>

In [19]:
tf.square(x_np*3).numpy() # to convert a tensor back to numpy

array([[9., 9., 9.],
       [9., 9., 9.]])

In [20]:
tf.convert_to_tensor(x_np) # to convert a numpy array back to tensor

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

#### Similarly u have many other math operations. tf.sqrt(x),tf.matmul, tf.exp()
#### https://www.tensorflow.org/api_docs/python/tf/math for a complete list

**Similar numpy universal functions & math operations**

https://numpy.org/doc/stable/reference/ufuncs.html

**What is the difference between numpy and tensorflow then?**

In [21]:
# TF Tensors
#------------
# Tensors are part of Tensorflow powerful library for ML/DL
# TensorFlow has a broad ecosystem designed for machine learning and deep learning, 
#...including tools like Keras, TensorFlow Lite for mobile, TensorFlow.js 
# Tensors can perform optimizations and hardware acceleration on CPU, GPU, TPU. 
# tensors are immutable. Useful for optimization in computation graphs..we will learn later
# Most important: Can compute gradients of any differentiable expression with respect to any of its inputs

#Numpy
#------------------------
# Numpy mainly designed for scientific computing and used extensively for Data science/ML/DL
# Numpy primarily  runs and optimized for cpu.  doesnt inherently support GPU accelation
# Numpy arrays are mutable
# Numpy cannot compute the gradients.

**Immutability**

In [22]:
tf.random.set_seed(5)
x = tf.random.uniform((2,2),0,3) # create a tensor filled with uniform values between 0 and 3
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.8791792, 1.5895296],
       [2.2753716, 1.5254653]], dtype=float32)>

In [23]:
# Now if u want to modify the created tensor, u cannot do it because its immutable
x[0,1] = 5

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [25]:
# But if its a numpy array, we can ofcouse modify a created array
np.random.seed(5)
x = np.random.uniform(0,3,size=(2,2))
x

array([[0.66597951, 2.61219692],
       [0.62015747, 2.75583272]])

In [26]:
x[0,1] = 5
x

array([[0.66597951, 5.        ],
       [0.62015747, 2.75583272]])

In [27]:
# There is a seperate class which is mutable and that is Tensorflow Variable.
# If the same array we create as a tensorflow variable, we can modify it
tf.random.set_seed(5)
x = tf.Variable(tf.random.uniform((2,2),0,3))
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1.8791792, 1.5895296],
       [2.2753716, 1.5254653]], dtype=float32)>

In [28]:
# we can modify a tensor variable. But we have to use the assign method to update it. 
# assign(), assign_add(), assign_sub() there are many such methods we can use to modify a tensorflow variable.
x[0,1].assign(5)
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1.8791792, 5.       ],
       [2.2753716, 1.5254653]], dtype=float32)>

In [29]:
# Any tensors that dont change, create them as contants
# Any tensors that you think will need to be updated or change, use tf.Variable

**Gradient calculation (using GradientTape())**

In [30]:
# Another important aspect of Tensorflow tensors. 
# you can calculate the gradient of any differential expression with respect to its inputs. 
#..U can't do this with nump array

In [31]:
# from physics lets say distance = 4*time^2, for an object moving with some speed
# What is the speed of the object? we take derivate of distance with respect to time, 
# ..lets say at time =2 sec

# lets do this with tensorflow GradientTape
t = tf.Variable(2.0)
with tf.GradientTape() as tape:
    d = 4*t**2
speed = tape.gradient(d,t)
speed

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [32]:
t = tf.Variable(2.0)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        d = 4*t**2
    speed = inner_tape.gradient(d,t)
acceleration =  outer_tape.gradient(speed,t)

print (f'Speed: {speed}')
print (f'Acceleration: {acceleration}')

Speed: 16.0
Acceleration: 8.0


In [ ]:
#So why is this important?
# for example to calculate the gradient of cost function dJ/dw

<img style="float: left;" src="./images/DL-Intuition3.png" Width="500">

<img style="float: left;" src="./images/cross_entropy_loss.png" Width="200">

<img style="float: left;" src="./images/forward_prop_equations.png" Width="900">



In [ ]:
# In principle we can build the entire deep learning model by training on any dataset using just tensorflow
# Because just like numpy it can do all kinds of tensor or basically math operations.

# and most importantly it can do gradient calculation required to do Gradient decent 

**Keras API**

Abstracts away all these low level tensor or math manipulations for building deep learning models

* Layers – To build the model or Network Architecture
* Loss function – Feedback signal for learning
* Optimizer – Determines how to use the loss function for updating weights
* Metrics – Evaluate model performance (Ex: Accuracy)
* Training loop – Loops over the training data in mini batches performing (forward propagation, backward propagation & updating weights)
